language: node_js
node_js: 6
cache:
  directories:
    - node_modules
install: npm install
script: npm test
notifications:
  email:
    recipients:
      - lovinghist@gmail.com
    on_success: never
    on_failure: always